language: php

dist: xenial 

sudo: false

services:
  - mysql

addons:
  apt:
    packages:
      - libxml2-utils
      
php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: master
  fast_finish: true
env:
  matrix:
    - LARAVEL_VERSION=5.6.* 
    - LARAVEL_VERSION=5.7.* 
    - LARAVEL_VERSION=5.8.*
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_script:
  - mysql_upgrade -u root 
  - mysql -h localhost -e "CREATE DATABASE forge;"
  - mysql -h localhost -e "CREATE USER forge@localhost"
  - mysql -h localhost -e "GRANT ALL PRIVILEGES ON forge.* TO forge@localhost;"
  - mysql -h localhost -e "FLUSH PRIVILEGES;"
  - composer clear-cache
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/framework:${LARAVEL_VERSION}" --no-update; fi;
  - travis_retry composer update $DEFAULT_COMPOSER_FLAGS
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer global require railken/cli-amethyst
  - composer global require railken/artisan
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml
  - ./vendor/bin/phpunit --configuration ./build/travis-ci-fail.xml > /dev/null; if [ $? -eq 0 ]; then echo "SHOULD FAIL"; false; else echo "fail checked"; fi;
  -  amethyst test --verbose

jobs:
  include:
    - stage: Quality
      php: 7.2
      script: composer update && amethyst test:phpstan --verbose
    - stage: Style
      php: 7.2
      script: composer update && amethyst test:style --verbose
    - stage: Deploy Documentation
      php: 7.2
      script:
        - php artisan amethyst:documentation:generate
        - php artisan amethyst:documentation:publishable
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs
        on:
          branch: master